'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Policy

    '''<summary>
    '''BackToRisk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BackToRisk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PolicyInfoFV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyInfoFV As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''PolicyInfoDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyInfoDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''AddPayrolBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddPayrolBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PayrollDataGV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PayrollDataGV As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''AddPayrollFV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddPayrollFV As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''PayrollDataDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PayrollDataDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''AddLossBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddLossBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LossDataGV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LossDataGV As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LossDataFV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LossDataFV As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''LossDataDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LossDataDS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
