'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QuickMod

    '''<summary>
    '''RiskSearchTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RiskSearchTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SearchBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AddRiskBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddRiskBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RiskSearchGV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RiskSearchGV As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''RiskSearchFV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RiskSearchFV As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''RiskSearchDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RiskSearchDS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
