'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Risk

    '''<summary>
    '''RiskInfoFV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RiskInfoFV As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''RiskInfoDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RiskInfoDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ProduceModBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProduceModBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModHistoryGV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModHistoryGV As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''WarningLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WarningLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EffectiveDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EffectiveDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EfectiveDateTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EfectiveDateTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ProduceModSubmitBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProduceModSubmitBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModHistoryDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModHistoryDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''AddPolicyBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddPolicyBT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PolicyHistoryGV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyHistoryGV As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PolicyHistoryDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyHistoryDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''AddPolicyFV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddPolicyFV As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''AddPolicyDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddPolicyDS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
